feat: tup-615 small header buttons (#338)
TACC/tup-ui pull request #339
Opened 2023-10-10 21:06 UTC by wesleyboar

## Overview

Make header spacing consistent.

## Related

- [TUP-615](https://jira.tacc.utexas.edu/browse/TUP-615)

## Changes

- #338

## Testing

1. …

## UI

…

2023-11-09 22:32 UTC, jarosenb approved these changes
Looks good in dev!

2023-11-09 22:40 UTC, jarosenb requested changes
We have an issue if the projects listing is large. It can crowd out the tickets and make them completely inaccessible: 
<img width="1613" alt="image" src="https://github.com/TACC/tup-ui/assets/12601812/18543c5e-2c87-4b11-a3eb-b1fbf54b4db9">
Maybe add a max-height on the project table?

2023-11-09 22:51 UTC, wesleyboar commented
I tested two fixes to [the problem you found](https://github.com/TACC/tup-ui/pull/339#pullrequestreview-1723624476).

**On the Grid:**
```css
.project-ticket-grid {
    ...
    grid-template-rows: minmax(auto, 200px) 1fr; /* instead of auto 1fr */
    ...
}
```

**On the Grid Item:**
```css
.project-ticket-grid:nth-child(1) {
    ...
    max-height: 200px;
}
```

2023-11-09 23:16 UTC, wesleyboar commented
New fix for narrow and wide screen (2689615). Slimmer and clearer I think.

https://github.com/TACC/tup-ui/assets/62723358/52a38bbb-44bf-4e47-bb27-c9fed4b5393d

2023-11-14 17:25 UTC, R-Tomas-Gonzalez reviewed
Question on headers and consistency. I noticed that some headers have nested headers, and some do not. The headers that are **not** nested, seem to have padding-right, due to being within articles. The headers that **are** nested, span the whole width of the page. Right padding may not matter. But thought I'd mention it.
 Here are the examples:
 
<img width="2340" alt="Screenshot 2023-11-14 at 11 20 06 AM" src="https://github.com/TACC/tup-ui/assets/63771558/267d92fa-1ea0-4099-b301-bf68aabd8621">
<img width="2343" alt="Screenshot 2023-11-14 at 11 19 10 AM" src="https://github.com/TACC/tup-ui/assets/63771558/69456c7b-88ec-423c-8733-61b6eaeb906b">
<img width="2341" alt="Screenshot 2023-11-14 at 11 19 50 AM" src="https://github.com/TACC/tup-ui/assets/63771558/f51bb86b-e7b4-49be-b7cf-cbb49b6525f5">
<img width="2339" alt="Screenshot 2023-11-14 at 11 19 33 AM" src="https://github.com/TACC/tup-ui/assets/63771558/e6eca085-838e-46e9-9aca-dd0687619bfe">

2023-11-14 17:29 UTC, R-Tomas-Gonzalez commented
*Note:* 

- https://github.com/TACC/tup-ui/pull/338
- https://github.com/TACC/tup-ui/pull/340
- https://github.com/TACC/tup-ui/pull/341 _(except for comment above)_
- https://github.com/TACC/tup-ui/pull/342
- [fix: project ticket grid too much middle space (f027640)](https://github.com/TACC/tup-ui/pull/339/commits/f027640b0a3991ba770f8758450b6e0d02408185)

All look good to me

2023-11-14 17:33 UTC, wesleyboar commented
Hm, thanks @R-Tomas-Gonzalez for https://github.com/TACC/tup-ui/pull/339#pullrequestreview-1730311908.

I did not pay attention to the right side of the headers…

I'll check this, and how #335 interacts with it.

2023-11-14 21:43 UTC, wesleyboar commented
@R-Tomas-Gonzalez What do you think consistent space on the right being handled in a new ticket instead of this one?

<details><summary>My reasoning…</summary>

- original ticket was focused on left and vertical
- this PR seems to be a valid fix for left and vertical
- i think it may be easier to tackle right-hand side in isolation
- i think it will be easier to tackle right-hand side after merges of existing PRs
</details>

2023-11-14 21:47 UTC, R-Tomas-Gonzalez commented
> @R-Tomas-Gonzalez What do you think consistent space on the right being handled in a new ticket instead of this one?
> 
> My reasoning…
> * original ticket was focused on left and vertical
> * this PR seems to be a valid fix for left and vertical
> * i think it may be easier to tackle right-hand side in isolation
> * i think it will be easier to tackle right-hand side after merges of existing PRs

I agree. 👍 :)

2023-11-14 21:50 UTC, R-Tomas-Gonzalez commented
Will approve when conflicts are resolved.

2023-11-14 21:57 UTC, wesleyboar commented
New ticket: [TUP-651](https://jira.tacc.utexas.edu/browse/TUP-651)
Consistent Spacing on Right for Section Headers

2023-11-14 22:27 UTC, R-Tomas-Gonzalez approved these changes

2023-11-14 22:39 UTC, jarosenb approved these changes
Approving now that long project lists no longer overflow the column.

2023-11-14 22:45 UTC, wesleyboar commented
> **Warning**
> Do not merge. Diff has accidental merge of CSS migration via 0e84c10.

2023-11-14 22:56 UTC, wesleyboar commented
> **Important**
> Safe to merge. Problem resolved. I reverted 0e222ee via f6b7bd5. Retested. Re-reviewed diff.

2023-11-14 23:07 UTC, wesleyboar commented on apps/tup-ui/src/pages/Dashboard/Dashboard.module.css
> +    grid-template-columns: 0.6fr 0.4fr;
This performs #369 **again**, but is tested at 100% zoom. ✔️ #369 was tested at 90% zoom. 🫤

2023-11-14 23:11 UTC, merged