task/TUP-194: Integrate dashboard login with Django user model
TACC/tup-ui pull request #49
Opened 2022-08-19 22:09 UTC by jarosenb

## Overview:
Integrates TUP-UI login with the TUP-CMS user model. The flow works like this: 
1. The user tries to visit a protected route (anything other than `/dashboard/login` for now).
2. They get bounced and redirected to `/dashboard/login` if their `x-tup-token` cookie is invalid.
3. Upon authenticating, they are redirected to the dashboard using `window.location.replace()`, causing the Django authentication background to login their user (or create it if it doesn't exist).

## Related:

- [TUP-194](https://jira.tacc.utexas.edu/browse/TUP-194)

## Changes:
- Refactor `LoginComponent` to use the `window.location` API to redirect instead of the history API. This is necessary for the Django backend to recognize the login event.
- Add a custom authentication backend that checks the user's `x-tup-token` cookie and validates it against the TUP-services API.
- Add a new `RestrictedView` that attempts to authenticate the user and redirects to `/dashboard/login` otherwise. 

## Testing:

1. Navigate to `localhost:8000/dashboard/` and confirm that you are redirected to a login page.
2. Log in using your TACC credentials and confirm that you are redirected to your profile page.
3. Log out and log back in to check that the auth flow works as expected.

2022-08-22 14:57 UTC, jchuahtacc commented on apps/tup-cms/src/apps/dashboard/views.py
> +def LoginView(request):
Is this already covered by Django's built in LoginView?

https://docs.djangoproject.com/en/4.1/topics/auth/default/#django.contrib.auth.views.LoginView

2022-08-22 14:57 UTC, jchuahtacc commented on apps/tup-cms/src/apps/dashboard/views.py
> +        return redirect('/dashboard/login')
Can this be a setting?

2022-08-22 14:57 UTC, jchuahtacc commented on apps/tup-ui/src/components/auth/LoginComponent/LoginComponent.tsx
> +    window.location.replace(`/dashboard${from}`);
can this get a query param for `?next_page` which is the Django default via `django.contrib.auth.views.LoginView`? maybe something like:

```
const [ searchParams, setSearchParams ] = useSearchParams();
const next_page? = searchParams.get("next_page");

...
window.location.replace(`${next_page ?? `/dashboard${from}``);
```

2022-08-23 15:42 UTC, jchuahtacc commented on apps/tup-ui/src/components/auth/LoginComponent/LoginComponent.tsx
> +    from = searchParams.get('from') ?? '/dashboard';
The default `django.contrib.auth.REDIRECT_FIELD_NAME` is `next`. Can you test an interaction with the default `@login_required` decorator?

2022-08-29 18:47 UTC, wesleyboar requested changes
Please resolve duplicate `tup-cms` resources. I think merging `main` would do that.

2022-09-01 19:12 UTC, wesleyboar reviewed
I remove my request for changes.

But, I am unable to test that this works.

<details><summary>What I Tried… <sub>(click to toggle details)</sub></summary>

0. `npm ci`, `nx build core-components`, `nx build core-styles`, `nx serve tup-ui`.
1. Visiting http://localhost:3000/static/ (as `nx serve tup-ui` states) loads white screen and prints to console a warning:
    ```
    <Router basename="/dashboard"> is not able to match the URL "/static/" because it does not start with the basename, so the <Router> won't render anything.
    ```
2. Visiting http://localhost:8000/dashboard/ (as Testing steps state) returns a 404 page with debug info.
3. Visiting http://localhost:3000/dashboard/ (I am grasping for straws) returns a 404 page with:
    > The server is configured with a public base URL of /static/ - did you mean to visit [/static/dashboard/](http://localhost:3000/static/dashboard/) instead?
4. Visiting http://localhost:3000/static/dashboard/ (as 404 page suggests) loads white screen and prints to console a warning:
    ```
    <Router basename="/dashboard"> is not able to match the URL "/static/" because it does not start with the basename, so the <Router> won't render anything.
    ```
    (It looks like step 1.)

</details>

2022-09-07 15:14 UTC, wesleyboar reviewed
I am trying to remove my request for changes via this review "Comment".

_**Edit**: This attempt to "un-request" changes did not work 🫤_

2022-09-08 16:23 UTC, merged